spring:
  profiles:
    active: dev

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mybatis
#    username: root
#    password: admin
#    driverClassName: com.mysql.jdbc.Driver
#    max-active: 20
#    max-idle: 8
#    mix-idle: 8
#  thymeleaf:
#    mode: LEGACYHTML5